server:
  port: 8000

core:
  api:
    token: ${CORE_API_TOKEN:change-me}
  docker:
    pullTimeoutSeconds: 180
    wal: true
    busyTimeoutMs: 5000

spring:
  application:
    name: core-control
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/app/storage/app.db
  flyway:
    enabled: true
    locations: classpath:db/migration
    mixed: true

logging:
  level:
    root: INFO
    com.stetits.core: INFO

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui